title: builderer
description: a fast, dependency-free, build-file generator
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
github:
  repository_name: builderer
  repository_nwo:  builderer/builderer
  repository_url:  https://github.com/builderer/builderer
  is_project_page: true
  is_user_page: false
  show_examples: true
  examples_url: https://github.com/builderer/builderer-examples
  example_repository_nwo: builderer/builderer-examples